### ISSUE TITLE
Configure and enable Continuous Integration with Travis CI

### ISSUE THREAD

**Issue by hjneyra** [Fredy/IS2-Project#57]
- Integrar el repositorio GitHub con Travis CI
- Pueden ver una guía aquí https://docs.travis-ci.com/user/getting-started/

**Comment by hjneyra** [comment]
Revisen este proyecto que ya tiene habilitado Travis CI https://github.com/gabrielfeitosa/ci-spring-boot
- Revisen especialmente los archivos `Procfile `, `Dockerfile` y `.travis.yml`

**Comment by Fredy** [comment]
Done in 4006f5d69975ee993a0f6882beb6b4a15354428c
